# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170715_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='scope',
            field=models.CharField(default='', max_length=200),
        ),
    ]
