# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_suggestion_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='predicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
