# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20170930_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='isImporting',
            field=models.BooleanField(default=False),
        ),
    ]
