# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_prefix_occurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='backend',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Backend'),
        ),
        migrations.AddField(
            model_name='predicate',
            name='backend',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Backend'),
        ),
        migrations.AddField(
            model_name='subject',
            name='backend',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Backend'),
        ),
    ]
