# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_auto_20171031_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="getPredicateNamesFromRelation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backend",
            name="getSubjectNamesFromRelation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backend",
            name="predicateNameRelation",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="backend",
            name="subjectNameRelation",
            field=models.CharField(default="", max_length=200),
        ),
    ]
