# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20171031_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='predicateNameRelation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='backend',
            name='subjectNameRelation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
