# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_auto_20171031_1304"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="name",
        ),
        migrations.AddField(
            model_name="subject",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
