# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_auto_20171202_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="subjectOrderRelation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
