# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_backend_subjectorderrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relations', models.CharField(default='', max_length=500)),
                ('backend', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Backend')),
            ],
        ),
    ]
