# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_backend_getpatternsfromqlever"),
    ]

    operations = [
        migrations.AddField(
            model_name="pattern",
            name="internalId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
