# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_pattern_internalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='dynamicSuggestions',
            field=models.BooleanField(default=True),
        ),
    ]
