# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20180616_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='predicate',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='backend',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='getPatternsFromQLever',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='getPredicateNamesFromRelation',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='getSubjectNamesFromRelation',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='predicateNameRelation',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='subjectNameRelation',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='subjectOrderRelation',
        ),
        migrations.AlterField(
            model_name='backend',
            name='dynamicSuggestions',
            field=models.IntegerField(choices=[(2, '3. SPARQL & context sensitive entities'), (1, '2. SPARQL & context insensitive entities'), (0, '1. SPARQL syntax & keywords only')], default=True, help_text='If you want to disable the dynamic suggestions from QLever or QLever UI by default change this option.', verbose_name='Default suggestion mode'),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.DeleteModel(
            name='predicate',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
