# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20180919_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name_plural': 'Prefixes'},
        ),
    ]
