# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_auto_20181215_1127"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
    ]
