# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_auto_20181215_1127"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="link",
            new_name="content",
        ),
    ]
