# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0036_auto_20190106_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="objectName",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Relation that tells QLever UI the name of a object (without prefixes).",
                verbose_name="Object name relation",
            ),
        ),
    ]
