# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20190126_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='subjectName',
            field=models.TextField(blank=True, default='', help_text='Relation that tells QLever UI the name of a subject (without prefixes).', verbose_name='Subject name relation'),
        ),
    ]
