# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0038_auto_20190127_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="maxDefault",
            field=models.IntegerField(
                default=100,
                help_text="The default for how many lines are shown in the first request",
                verbose_name="Default Maximum",
            ),
        ),
    ]
