# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0041_auto_20190202_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="suggestObjects",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Clause that tells QLever UI which objects to suggest from (without prefixes). Only needed for suggestion mode 2 (context insensitive suggestions).<br>Qlever UI expects the following variables to be used:<br>&nbsp;&nbsp;- &nbsp;?qleverui_object: The objects that we want to suggest from<br>Your clause will be used as following:<br>SELECT ?qleverui_object (COUNT(?qleverui_object) AS ?qleverui_count) WHERE {<br>&nbsp;&nbsp;&nbsp;&nbsp;<b><em>suggest objects clause</em></b><br>}<br>GROUP BY ?qleverui_object<br>ORDER BY DESC(?qleverui_count)",
                verbose_name="Suggest objects clause",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="suggestSubjects",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Clause that tells QLever UI which subjects to suggest from (without prefixes). Leave blank if you don't want subject suggestions.<br>Qlever UI expects the following variables to be used:<br>&nbsp;&nbsp;- &nbsp;?qleverui_subject: The subjects that we want to suggest from<br>Your clause will be used as following:<br>SELECT ?qleverui_subject (COUNT(?qleverui_subject) AS ?qleverui_count) WHERE {<br>&nbsp;&nbsp;&nbsp;&nbsp;<b><em>suggest subjects clause</em></b><br>}<br>GROUP BY ?qleverui_subject<br>ORDER BY DESC(?qleverui_count)",
                verbose_name="Suggest subjects clause",
            ),
        ),
    ]
