# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0043_backend_filteredlanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="supportedFunctions",
            field=models.TextField(
                blank=True,
                default="asc, desc, avg, values, score, text, count, sample, min, max, average, concat, group_concat, langMatches, lang, regex, sum",
                help_text="Comma separated list of SPARQL functions supported by the backend. Will be used for funciton highlighting.",
                verbose_name="Supported functions",
            ),
        ),
        migrations.AddField(
            model_name="backend",
            name="supportedKeywords",
            field=models.TextField(
                blank=True,
                default="prefix, select, distinct, where, order, limit, offset, optional, by, as, having, not, textlimit, contains-entity, contains-word, filter, group, union, optional, has-predicate",
                help_text="Comma separated list of SPARQL keywords supported by the backend. Will be used for keyword highlighting.",
                verbose_name="Supported keywords",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="filteredLanguage",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="Comma separated language codes used for filter suggestions",
                max_length=2000,
                verbose_name="Filter languages",
            ),
        ),
    ]
