# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0045_auto_20190217_1158"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="filterEntities",
            field=models.BooleanField(
                default=False,
                verbose_name="Also suggest FILTER for variables that store entity IDs",
            ),
        ),
    ]
