# Generated by Django 3.0.2 on 2020-04-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_backend_supportedpredicatesuggestions'),
        ('backend', '0053_auto_20200215_1526'),
    ]

    operations = [
    ]
