# Generated by Django 3.0.2 on 2020-04-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0054_merge_20200424_1016"),
        ("backend", "0053_backend_suggestprefixnamesforpredicates"),
    ]

    operations = []
