# Generated by Django 3.0.2 on 2020-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_merge_20200425_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='suggestSubjectsInEmptyLine',
            field=models.BooleanField(
                default=False, help_text='Suggest subjects when no character has been typed yet.', verbose_name='Suggest subject in empty lines.'),
        ),
    ]
