# Generated by Django 3.0.2 on 2020-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_backend_suggestsubjectsinemptyline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='alternativeObjectName',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='alternativePredicateName',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='alternativeSubjectName',
        ),
        migrations.AlterField(
            model_name='backend',
            name='suggestSubjectsInEmptyLine',
            field=models.BooleanField(default=False, help_text='Suggest subjects when no character has been typed yet.', verbose_name='Suggest subjects in empty lines.'),
        ),
    ]
