# Generated by Django 3.0.2 on 2021-06-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20210605_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='isImporting',
        ),
        migrations.RemoveField(
            model_name='backend',
            name='ntFilePath',
        ),
        migrations.DeleteModel(
            name='Prefix',
        ),
    ]
