# Generated by Django 3.0.2 on 2021-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_auto_20210605_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='suggestionAltNameVariable',
            field=models.CharField(default='?qleverui_altname', help_text='The variable that stores the alternative name of the suggestion in the following queries.', max_length=100, verbose_name='Variable for alternative suggestion name'),
        ),
        migrations.AddField(
            model_name='backend',
            name='suggestionEntityVariable',
            field=models.CharField(default='?qleverui_entity', help_text='The variable that stores the suggested entity in the following queries.', max_length=100, verbose_name='Variable for suggestion name'),
        ),
        migrations.AddField(
            model_name='backend',
            name='suggestionNameVariable',
            field=models.CharField(default='?qleverui_name', help_text='The variable that stores the name of the suggestion in the following queries.', max_length=100, verbose_name='Variable for suggestion name'),
        ),
        migrations.AddField(
            model_name='backend',
            name='suggestionReversedVariable',
            field=models.CharField(default='?qleverui_reversed', help_text='The variable that stores wether a suggestion is reversed.', max_length=100, verbose_name='Variable for reversed suggestion'),
        ),
    ]
