# Generated by Django 3.0.2 on 2021-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0062_auto_20210606_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="entityNameAndAliasPattern",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="entityNameAndAliasPatternDefault",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="entityScorePattern",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="frequentPatternsWithoutOrder",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="frequentPredicates",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithContext",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithContextDefault",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithoutContext",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithoutContextDefault",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="warmupQuery1",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="warmupQuery2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="warmupQuery3",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="warmupQuery4",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backend",
            name="warmupQuery5",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="backend",
            name="suggestedPrefixes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A list of prefixes that should be suggested. Prefixes can have either of these forms:<ul><li>@prefix schema: &lt;https://www.schema.org/&gt; .</li><li>Prefix schema: &lt;http://schema.org/&gt;</li></ul>",
                verbose_name="Suggested Prefixes",
            ),
        ),
    ]
