# Generated by Django 3.0.2 on 2021-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0063_auto_20210620_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="entityNameAndAliasPattern",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %ENTITY_NAME_AND_ALIAS_PATTERN%",
                verbose_name="Entity name and alias pattern",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="entityNameAndAliasPatternDefault",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %ENTITY_NAME_AND_ALIAS_PATTERN_DEFAULT%",
                verbose_name="Entity name and alias pattern (default)",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="entityScorePattern",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %ENTITY_SCORE_PATTERN%",
                verbose_name="Entity score pattern",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="frequentPatternsWithoutOrder",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Frequent patterns without order",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="frequentPredicates",
            field=models.TextField(
                blank=True, default="", verbose_name="Frequent predicates"
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithContext",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %PREDICATE_NAME_AND_ALIAS_PATTERN_WITH_CONTEXT%",
                verbose_name="Predicate name and alias pattern with context",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithContextDefault",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %PREDICATE_NAME_AND_ALIAS_PATTERN_WITH_CONTEXT_DEFAULT%",
                verbose_name="Predicate name and alias pattern with context (default)",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithoutContext",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %PREDICATE_NAME_AND_ALIAS_PATTERN_WITHOUT_CONTEXT%",
                verbose_name="Predicate name and alias pattern without context",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="predicateNameAndAliasPatternWithoutContextDefault",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %PREDICATE_NAME_AND_ALIAS_PATTERN_WITHOUT_CONTEXT_DEFAULT%",
                verbose_name="Predicate name and alias pattern without context (default)",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="warmupQuery1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %WARMUP_QUERY_1%",
                verbose_name="Warmup query 1",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="warmupQuery2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %WARMUP_QUERY_2%",
                verbose_name="Warmup query 2",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="warmupQuery3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %WARMUP_QUERY_3%",
                verbose_name="Warmup query 3",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="warmupQuery4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %WARMUP_QUERY_4%",
                verbose_name="Warmup query 4",
            ),
        ),
        migrations.AlterField(
            model_name="backend",
            name="warmupQuery5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Use in warmup and autocomplete queries by typing %WARMUP_QUERY_5%",
                verbose_name="Warmup query 5",
            ),
        ),
    ]
