# Generated by Django 3.2.5 on 2021-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0065_auto_20210626_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="dynamicSuggestions",
            field=models.IntegerField(
                choices=[
                    (3, "4. Mixed mode"),
                    (2, "3. SPARQL & context sensitive entities"),
                    (1, "2. SPARQL & context insensitive entities"),
                    (0, "1. SPARQL syntax & keywords only"),
                ],
                default=2,
                help_text="If you want to disable the dynamic suggestions from QLever or QLever UI by default change this option.",
                verbose_name="Default suggestion mode",
            ),
        ),
    ]
