# Generated by Django 3.2.5 on 2021-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_backend_mixedmodetimeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='defaultModeTimeout',
            field=models.FloatField(default=0, help_text='The timeout in seconds for autosuggestion queries.', verbose_name='Mixed mode timeout'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='mixedModeTimeout',
            field=models.FloatField(default=1, help_text='The timeout in seconds for the main query in mixed mode.', verbose_name='Mixed mode timeout'),
        ),
    ]
