# Generated by Django 5.0.3 on 2024-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0072_backend_isnoslugmode"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="enableMapView",
            field=models.BooleanField(
                default=False,
                help_text="Show the 'Map view' button for this dataset if the last column of the results contains WKT literals.",
                verbose_name="Enable 'Map view' button",
            ),
        ),
        migrations.AddField(
            model_name="backend",
            name="mapViewBaseURL",
            field=models.CharField(
                blank=True,
                default="https://qlever.cs.uni-freiburg.de/mapui-petri/",
                help_text="The base URL for the Map view including a trailing slash (/).",
                max_length=2048,
                verbose_name="Map view base URL",
            ),
        ),
    ]
