# Generated by Django 5.0.3 on 2025-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0075_alter_example_sortkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="supportedKeywords",
            field=models.TextField(
                blank=True,
                default="as, base, bind, by, construct, contains-entity, contains-word, data, delete, distinct, filter, from, graph, group, has-predicate, having, insert, internal, keywords, limit, minus, named, not, offset, optional, optional, order, prefix, select, service, sort, textlimit, union, using, values, where, with",
                help_text="Comma separated list of SPARQL keywords supported by the backend. Will be used for keyword highlighting.",
                verbose_name="Supported keywords",
            ),
        ),
    ]
